164 - Extract camera scanner from core library keeping the same activity
enioka-Haute-Couture/enioka_scan pull request #176
Opened 2024-04-19 15:24 UTC by VincentKobz

-  Create a maven artifact `scanner-camera`, which contains all camera-related classes (*camera SDK* and the new *CameraProvider* class)
- Refactor `ScannerCompatActivity`: check at runtime if the camera SDK is included. Explicitly get the `CameraProvider` which implements the `CameraScanner` interface, to facilitate communication between *AppCompatActivity* and the camera scanner.
- Create `CameraScannerProvider` in `scanner-camera` (`com.enioka.scanner.sdk.camera`), which contains the implementation of the `CameraProvider` interface. This class allows the activity to interact with the `CameraBarcodeScanViewScanner` (set the *statusCallback*, *pause*, *resume* ect.).
- Update the ReadTheDocs documentation to match the new API.

Change inside `ScannerCompatActivity`:
- Interaction buttons for scanners will now be disable if no scanner provider is found.
- Camera toggle button only shows if the *camera SDK* is found.

The entire camera scanner API is still accessible, via the `scanner-camer` artifact.

2024-04-23 15:54 UTC, DaSpood requested changes

2024-04-23 15:54 UTC, DaSpood commented on docs/api/scanner_activity.md
> +If the camera SDK is included, it will be defined to :::{cpp:var}R.id.camera_scan_view
```suggestion
If the camera SDK is included, it will be set to :::{cpp:var}R.id.camera_scan_view
```

2024-04-23 15:54 UTC, DaSpood commented on docs/api/scanner_activity.md
> +If the camera SDK is included, it will be defined to :::{cpp:var}R.id.scanner_switch_zxing.
```suggestion
If the camera SDK is included, it will be set to :::{cpp:var}R.id.scanner_switch_zxing.
```

2024-04-23 15:54 UTC, DaSpood commented on docs/api/scanner_activity.md
> +It is the ID of the optional toggle button on which to press to pause/unpause the scanner.
```suggestion
The ID of the optional toggle button on which to press to pause/unpause the scanner.
```

Attention ici, on peut vouloir le switch meme sans la camera, il sert uniquement a appeler `scanner.pause()` / `scanner.resume()`. Jusqu'ici il était en vue camera, mais techniquement rien n’empêche de l'utiliser ailleurs, ce n’était qu'une implementation par défaut.

Si on veut garder l'assignation automatique en cas de presence de la camera, il faut preciser que c'est un comportement par defaut qui doit pouvoir s'override.

2024-04-23 15:54 UTC, DaSpood commented on docs/api/scanner_activity.md
> +The optional instance of the camera scanner provider, is defined if the camera SDK is included.
```suggestion
The optional instance of the camera scanner provider, is set if the camera SDK is included.
```

2024-04-23 15:54 UTC, DaSpood commented on docs/dependencies.md
> +default camera layout for scanner activity.
```suggestion
default camera layout for the scanner activity.
```

2024-04-23 15:54 UTC, DaSpood commented on docs/dependencies.md
> +| `scanner-camera`                   | `CAMERA_SCANNER` (no provider)   | Any device with a camera                            | Smartphones, integrated devices... | Camera        |
Garder une ligne avec l'artefact "core" en précisant bien qu'il ne supporte aucun SDK par défaut mais est nécessaire a l'utilisation de la lib, et contient notamment le service qui gère la recherche et le lifecycle des scanners (comme la recherche fonctionne par intent, il est il me semble possible de détecter des SDK qui ne sont pas forcement presents dans l'application).

2024-04-23 15:54 UTC, DaSpood commented on docs/quickstart.md
> +for a detailed overview.
```suggestion
Additional device-specific dependencies are required to enable support for actual scanners.
You can check the [library dependencies and compatibility matrix](dependencies.md)
for a detailed overview.
```

2024-04-23 15:54 UTC, DaSpood commented on enioka_scan/src/main/java/com/enioka/scanner/sdk/camera/CameraScanner.java
> +public interface CameraScanner {
```suggestion
public interface CameraScannerProvider {
```

2024-04-24 11:34 UTC, VincentKobz commented on docs/api/scanner_activity.md
> +It is the ID of the optional toggle button on which to press to pause/unpause the scanner.
Ok ! Je pensais que c'etait un mode uniquement utile au scanner camera, je n'avais pas fait attention. Je vais rectifier cela.

2024-04-29 07:47 UTC, DaSpood requested changes

2024-04-29 07:47 UTC, DaSpood commented on docs/dependencies.md
> +| `core`                             | `CORE` (no provider)             | Does not support any device alone, it required to use the lib. |                                    |               |
```suggestion
| `core`                             | no provider             | Does not support any device alone, it is a required dependency. |                                    |               |                                                                |                                                                                                                                   |
```

Verifier que le nom d'artefact `core` corresponde bien a l'artefact qui sera publish sur maven (actuellement: `scanner`)

2024-04-30 13:37 UTC, DaSpood approved these changes

2024-04-30 13:39 UTC, merged