68 - Add missing symbologies in SDKs
enioka-Haute-Couture/enioka_scan pull request #194
Opened 2024-06-10 09:16 UTC by VincentKobz

https://github.com/enioka-Haute-Couture/enioka_scan/issues/68

- List of supported symbologies inside `enioka_scan` core:
```
CODE39
CODE 39 FULL ASCII
CODE 11
CODE93
CODE128
CODABAR
INT25 (code 25 interleaved)
DIS25 (code 25 industrial ?)
QRCODE
UPCA
UPCE
EAN8
EAN13
DATAMATRIX
MAXICODE
GS1 DATABAR EXPANDED
GS1 DATABAR
GS1 DATABAR LIMITED
ISBN10
GS1 128
MSI
PDF147
AZTEC
AZTEC RUNNER
JAPAN POSTAL
DUTCH POSTAL
UK POSTAL
AUSTRALIA POSTAL
KOREAN POSTAL
CHINA POSTAL
CANADIAN POSTAL
HAN XIN
```
Added these symbologies where supported in SDKs:
- `provider-os-athesi-spa43`
- `provider-os-honeywell-integrated`
- `provider-cs-proglove`
- `provider-cs-honeywell`
- `provider-cs-koamtac`
- `provider-cs-zebra`
- `provider-os-zebra-dw`
- `provider-os-camera` (Zxing and Zbar)

2024-06-10 12:19 UTC, VincentKobz commented on docs/dependencies.md
> +## Supported barcode types
Should we put `supported barcode types` section here ?

2024-06-26 07:43 UTC, DaSpood requested changes

2024-06-26 07:43 UTC, DaSpood commented on enioka_scan/src/main/java/com/enioka/scanner/data/BarcodeType.java
>       */
Commentaire a retirer

2024-06-26 07:43 UTC, DaSpood commented on enioka_scan_honeywelloss_integrated/src/main/java/com/enioka/scanner/sdk/honeywelloss/integrated/SymbologyId.java
>              return BarcodeType.CODE128;
remplacer la chaine de "if" par un switch ou comme pour les autres SDK passer par une hashmap pour rendre la conversion plus rapide.

2024-06-26 07:43 UTC, DaSpood commented on enioka_scan_honeywelloss_spp/src/main/java/com/enioka/scanner/sdk/honeywelloss/spp/SymbologyId.java
> +        if (symbologyString.equals("KOREA_POST"))
remplacer la chaine de "if" par un switch ou comme pour les autres SDK passer par une hashmap pour rendre la conversion plus rapide.

2024-06-26 09:14 UTC, VincentKobz commented on enioka_scan_honeywelloss_integrated/src/main/java/com/enioka/scanner/sdk/honeywelloss/integrated/SymbologyId.java
>          put(0x42, "BRITISH_POST"); //B
Est-il necessaire de faire un map entre l'ID honeywell et sa symbology en `String`, plutot que de directement  map l'`enum` correspondant ?

2024-07-01 09:00 UTC, DaSpood commented on enioka_scan_honeywelloss_integrated/src/main/java/com/enioka/scanner/sdk/honeywelloss/integrated/SymbologyId.java
>          put(0x42, "BRITISH_POST"); //B
Ca doit etre un residu de l'epoque ou on cherchait a reverse le protocole en comparant avec la doc, effectivement maintenant qu'on supporte toutes les symbologies on pourrait s'en passer.

2024-07-01 09:03 UTC, DaSpood approved these changes

2024-07-01 09:08 UTC, merged