197 update documentation
enioka-Haute-Couture/enioka_scan pull request #199
Opened 2024-06-14 15:04 UTC by VincentKobz

2024-07-03 13:27 UTC, DaSpood requested changes

2024-07-03 13:27 UTC, DaSpood commented on enioka_scan/src/main/java/com/enioka/scanner/activities/ScannerCompatActivity.java
> +            cameraResources = new HashMap<>();
Commit ce5167c915724afcb5d8cd432b51a6b72c1e1323: la NPE ne peut normalement pas se produire: la hashmap est set dans `OnStart()`, il ne faut pas la reinitialiser ici.

2024-07-03 13:27 UTC, DaSpood commented on enioka_scan/src/main/java/com/enioka/scanner/activities/ManualInputFragment.java
Commit b929f196c3539bf15c421ac66efb56287f1eb1ef: on veut quand meme garder (il me semble) la possibilite d'input manuellement un code barre dans le cas ou le scanner n'arrive pas a le lire (c'est pour ca qu'en general le contenu du code barre est ecrite sous le code barre en question). Ca me fait du coup remarquer que cette fonctionnalite n'existe plus dans l'app demo, je n'y avais pas fait gaffe mais il faudrait la reintegrer (dans une autre PR). Pour le moment, revert cette partie du commit, ok pour le reste du deadcode (y compris l'autocompletion car `@unused`) mais pas l'input manuel. Attention a aussi remettre la doc associee.

2024-07-03 13:27 UTC, DaSpood commented on docs/api/scanner_activity.md
> +- `-1`: The preview aspect ratio mode is not set. The default value will be used.
La default value (0) doit etre assignee par defaut, autrement ce n'est pas une default value, ici -1 est equivalent a 0. My bad si j'ai laisse passer ce detail dans une precedente review.

2024-07-04 08:46 UTC, VincentKobz commented on enioka_scan/src/main/java/com/enioka/scanner/activities/ScannerCompatActivity.java
> +            cameraResources = new HashMap<>();
Le `onCreate` est call avant le `onStart`, donc je peux juste init le hashmap si `cameraResources` est null.

2024-07-04 09:14 UTC, DaSpood commented on enioka_scan/src/main/java/com/enioka/scanner/activities/ScannerCompatActivity.java
> +            cameraResources = new HashMap<>();
Dans ce cas faire un appel a `setCameraViewId();` plutot qu'une hashmap vide pour etre sur d'avoir le meme comportement

2024-07-08 13:04 UTC, DaSpood approved these changes

2024-07-08 13:04 UTC, merged