221 cordova capacitor react integration
enioka-Haute-Couture/enioka_scan pull request #224
Opened 2024-10-17 11:51 UTC by NathanFortyTwo

Address issues #223  #222  and #221 

Adds code to be able to use ScannerCompatActivity, and enioka-scan services, from an already existing application in cordova, capacitor and react-native using npm packages

Cordova and Capacitor use compatible plugin system so only one package is needed

2024-10-17 13:20 UTC, DaSpood requested changes

2024-10-17 13:20 UTC, DaSpood commented on npm_integration_frameworks/cordova-capacitor/src/android/ActivityStarterPlugin.java
> +            Intent intent = new Intent(this.cordova.getContext(), klass);
Ca pourrait etre bien de supporter un bundle / des extras a integrer a cet intent, pour permettre a l'utilisateur de controller les options de l'application (voir app de demo pour comment ce serait utilise). C'est ok si pas evident tout de suite, ca peut attendre une autre MR.

2024-10-17 13:20 UTC, DaSpood commented on npm_integration_frameworks/reactnative/android/gradle.properties
> +ActivityStarter_compileSdkVersion=31
On va preferer reprendre les versions de la lib core plutot que de l'appli de demo (qui est plus elevee uniquement pour pouvoir passer sur le play store):

```suggestion
ActivityStarter_minSdkVersion=19
ActivityStarter_targetSdkVersion=28
ActivityStarter_compileSdkVersion=28
```

2024-10-17 13:20 UTC, DaSpood commented on npm_integration_frameworks/reactnative/android/src/main/java/com/activitystarter/ActivityStarterModule.java
> +            Intent intent = new Intent(activity, klass);
Comme pour Cordova, si possible on aimerait donner plus de controle a l'utilisateur avec le support d'intent extras / bundles comme ce qui est fait dans l'app de demo pour appliquer les parametres au service.

2024-10-17 13:20 UTC, DaSpood commented on npm_integration_frameworks/reactnative/lefthook.yml
> +pre-commit:
Pas necessaire pour notre cas d'usage, a supprimer

2024-10-17 13:20 UTC, DaSpood commented on npm_integration_frameworks/reactnative/package.json
> +{
a nettoyer au maximum pour ne conserver que le strict necessaire pour le plugin npm

2024-10-17 13:20 UTC, DaSpood commented on npm_integration_frameworks/reactnative/src/__tests__/index.test.tsx
> +it.todo('write a test');
Pas necessaire, a supprimer

2024-10-17 15:57 UTC, NathanFortyTwo commented
bundle/extras pas encore intégrés aux Intent dans startActivity, 
Je ne suis pas sur de comment récupérer le bundle depuis le code utilisateur.

2024-10-23 08:42 UTC, DaSpood approved these changes

2024-10-23 08:54 UTC, merged